import { Campaign } from "@/types/types";

export const mockCampaigns: Campaign[] = [
  {
    id: "1",
    title: "Warm Hearts Drive",
    description: "Collecting jackets and blankets for the homeless.",
    charityID: "C1",
    startDate: "2025-10-01",
    endDate: "2025-11-01",
    createdAt: "2025-09-30",
    neededItems: [
      { id: 1, name: "T-shirts" },
      { id: 2, name: "Blankets" },
      { id: 3, name: "Jackets" },
    ],
  },
  {
    id: "2",
    title: "Books for Change",
    description: "Donating educational materials to underfunded schools.",
    charityID: "C2",
    startDate: "2025-09-15",
    endDate: "2025-12-15",
    createdAt: "2025-09-10",
    neededItems: [
      { id: 4, name: "Math books" },
      { id: 5, name: "Storybooks" },
      { id: 6, name: "Notebooks" },
    ],
  },
  {
    id: "3",
    title: "Feeding Futures",
    description: "Providing weekly meals to families in need.",
    charityID: "C3",
    startDate: "2025-08-01",
    endDate: "2025-12-31",
    createdAt: "2025-07-25",
    neededItems: [
      { id: 7, name: "Rice" },
      { id: 8, name: "Canned goods" },
      { id: 9, name: "Cooking oil" },
    ],
  },
  {
    id: "4",
    title: "Paws and Hearts",
    description: "Supporting local shelters with pet food donations.",
    charityID: "C4",
    startDate: "2025-10-10",
    endDate: "2025-11-20",
    createdAt: "2025-10-01",
    neededItems: [
      { id: 10, name: "Dog food" },
      { id: 11, name: "Cat food" },
      { id: 12, name: "Pet toys" },
    ],
  },
  {
    id: "5",
    title: "Green Tomorrow",
    description: "Tree-planting and environmental cleanup drive.",
    charityID: "C5",
    startDate: "2025-11-05",
    endDate: "2025-12-05",
    createdAt: "2025-10-15",
    neededItems: [
      { id: 13, name: "Seedlings" },
      { id: 14, name: "Shovels" },
      { id: 15, name: "Gloves" },
    ],
  },
  {
    id: "6",
    title: "Toy Joy Project",
    description: "Spreading smiles by gifting toys to children in hospitals.",
    charityID: "C6",
    startDate: "2025-11-01",
    endDate: "2025-12-25",
    createdAt: "2025-10-20",
    neededItems: [
      { id: 16, name: "Plushies" },
      { id: 17, name: "Board games" },
      { id: 18, name: "Coloring books" },
    ],
  },
  {
    id: "7",
    title: "Light of Learning",
    description: "Providing solar lamps to off-grid rural students.",
    charityID: "C7",
    startDate: "2025-09-10",
    endDate: "2025-11-30",
    createdAt: "2025-09-01",
    neededItems: [
      { id: 19, name: "Solar lamps" },
      { id: 20, name: "Batteries" },
      { id: 21, name: "Extension cords" },
    ],
  },
  {
    id: "8",
    title: "Water for All",
    description: "Building wells and providing clean drinking water systems.",
    charityID: "C8",
    startDate: "2025-10-20",
    endDate: "2026-01-15",
    createdAt: "2025-10-10",
    neededItems: [
      { id: 22, name: "Water filters" },
      { id: 23, name: "Pipes" },
      { id: 24, name: "Buckets" },
    ],
  },
  {
    id: "9",
    title: "Care Kits Campaign",
    description: "Distributing hygiene kits to disaster-affected families.",
    charityID: "C9",
    startDate: "2025-09-01",
    endDate: "2025-10-30",
    createdAt: "2025-08-25",
    neededItems: [
      { id: 25, name: "Soap" },
      { id: 26, name: "Toothpaste" },
      { id: 27, name: "Towels" },
    ],
  },
  {
    id: "10",
    title: "Hope in Tech",
    description: "Collecting old but working gadgets for student learning.",
    charityID: "C10",
    startDate: "2025-08-20",
    endDate: "2025-12-31",
    createdAt: "2025-08-10",
    neededItems: [
      { id: 28, name: "Laptops" },
      { id: 29, name: "Chargers" },
      { id: 30, name: "Headphones" },
    ],
  },
];
